logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


#spring:
#  zipkin:
#    base-url: http://localhost:9411/
#  output:
#    ansi:
#      enabled: always
      
server:
  port: 8081
#  servlet: 
#    context-path: /sleuth-upstream-service
 